PID for Tron Guy Labs M122/3270 USB keyboard
pidcodes/pidcodes.github.com pull request #656
Opened 2021-06-13 11:03 UTC by jmaynard

Requesting PID 1209/3270 for a controller board for the IBM Model M 122-key keyboard. This isn't a converter, but replaces the internal controller entirely. It uses the open-source QMK firmware. My code is in the QMK repository I linked, in the keyboards/handwired/ibm122m/keymaps/jmaynard/ directory.

2021-07-14 01:54 UTC, tannewt requested changes
Please include the modifiable EasyEDA files from here: https://easyeda.com/dillon/Backup_Your_EasyEDA_Project_Locally-JrecamWv5

Please also link to the hardware files from here and link to the QMK files from the readme of the hardware source. That will make it easier to find the hardware from the pid.codes website.

2021-07-14 02:42 UTC, jmaynard commented
> Please include the modifiable EasyEDA files from here: https://easyeda.com/dillon/Backup_Your_EasyEDA_Project_Locally-JrecamWv5
> 
> Please also link to the hardware files from here and link to the QMK files from the readme of the hardware source. That will make it easier to find the hardware from the pid.codes website.

I have a pull request in for the QMK sources that's waiting on approval of this PR to get merged into their repository. We have a chicken and egg situation. Shall I link to my QMK fork, or...?

2021-07-16 21:55 UTC, jmaynard commented
> > Please include the modifiable EasyEDA files from here: https://easyeda.com/dillon/Backup_Your_EasyEDA_Project_Locally-JrecamWv5
> > Please also link to the hardware files from here and link to the QMK files from the readme of the hardware source. That will make it easier to find the hardware from the pid.codes website.
> 
> I have a pull request in for the QMK sources that's waiting on approval of this PR to get merged into their repository. We have a chicken and egg situation. Shall I link to my QMK fork, or...?

For now, I've linked to my QMK fork. I also added the EasyEDA files to the hardware repository, and linked my QMK fork from my hardware repository; once this PR and the QMK PR are approved, I'l move the link on the hardware to the proper place in the QMK tree.

2021-07-22 11:27 UTC, jmaynard commented
The code has now been merged to the QMK tree, and I've updated the links from the hardware repository and this PR to point to it.

2021-07-31 23:50 UTC, tannewt approved these changes
Looks good. Thanks for the update

2021-07-31 23:50 UTC, merged