Pi-KVMD organization and IDs
pidcodes/pidcodes.github.com pull request #660
Opened 2021-07-11 13:24 UTC by mdevaev

Hi! Pi-KVM is a project to create an open KVM based on Raspberry Pi. All software is distributed under the GPLv3 license, the basic schematic technology is also open.

I'm asking you to allocate two identifiers for different USB emulation devices. They will be used to make it easier for system administrators to distinguish them from generic Arduino and other OTG devices.

2021-07-14 02:06 UTC, tannewt requested changes
Where are the hardware files for the V3 HAT?

2021-07-14 05:44 UTC, mdevaev commented
V3 hat is a commerical hardware which uses open source software. This is a separate project. I'm not asking for a PID for this, but specifically for software that people already use in their DIY KVM. Schemes v0 and v2 are open.

2021-07-31 23:58 UTC, tannewt approved these changes
Ok. Please do not use this PID for images meant for the closed, commercial V3 hardware. These PIDs are for open hardware projects only.

2021-07-31 23:58 UTC, merged

2021-08-01 00:46 UTC, mdevaev commented
@tannewt Thanks, but the last thing I want to do is break your rules :) I really can't use this even if the v3 firmware is completely open and the codes are part of it, and not flashed on hardware? Firmware v2 and v3 have no differences on the part of the software and differ only in a couple of lines in the configuration files.

2021-08-13 19:11 UTC, tannewt commented
The goal of pid.codes is to promote open hardware by granting PIDs. You should open source your hardware if you want to use a pid.codes PID on it. If you don't want to because of commercial reasons, then you should be willing to pay for a commercial PID. It's another cost of doing business. Most microcontroller manufacturers will sublicense you one (some for free.)

2021-08-13 21:56 UTC, mdevaev commented
Got it.