PID Request: 2730 for RubyLink
pidcodes/pidcodes.github.com pull request #710
Opened 2021-12-27 06:33 UTC by Misaka0x2730

Hello!
I'm requesting PID 0x2730 for the RubyLink, USB/Ethernet ARM debugger with 2 target interfaces (one is isolated) based on RP2040.
The firmware is under development, but the firmware is based on [BlackMagic Probe firmware](https://github.com/blacksphere/blackmagic/)

Link to hardware: https://github.com/Misaka0x2730/RubyLink

This hardware is licensed under CERN-OHL-P.

Thank you!

2022-01-06 18:44 UTC, tannewt requested changes
Where is the firmware that is under development available? Please link to it from your hardware's README.

2022-01-06 18:48 UTC, Misaka0x2730 commented
> Where is the firmware that is under development available? Please link to it from your hardware's README.

I have not updated [the repo](https://github.com/Misaka0x2730/Miyako-Link) yet, okay, thanks, I will update the repo tomorrow and add the link to hardware's README.

2022-01-07 19:35 UTC, Misaka0x2730 commented
@tannewt Done!

2022-02-14 02:46 UTC, tannewt approved these changes
Thank you!

2022-02-14 02:46 UTC, merged