Request PIDs for RF Chameleon
pidcodes/pidcodes.github.com pull request #916
Opened 2024-01-22 22:39 UTC by andysan

RF Chameleon is a small tool to interface with ISM-band devices. The tool currently consists of the following parts:

- [Firmware](https://github.com/rfchameleon/rfchameleon-fw) to interface with TI radios (currently only tested with the CC1101).
- A [custom board](https://github.com/rfchameleon/rfchameleon-hw) that can be used instead of a dev-board with a CC1101 module.
- A MCUboot-based bootloader convenient firmware upgrades.

The firmware is licensed under Apache 2.0 and the hardware under the Solderpad Hardware License 2.1 (aka Apache-2.0 WITH SHL-2.1).

This PR requests the following PIDs:

- 0x5F00 for the radio interface.
- 0x5F01 for the bootloader.

2024-02-01 19:00 UTC, tannewt requested changes
Kicad hardware files. Zephyr firmware. Where is the bootloader source? Is it custom?

2024-02-01 19:29 UTC, andysan commented
> Kicad hardware files. Zephyr firmware. Where is the bootloader source? Is it custom?

It's MCUBoot and built from the same tree as the main firmware. However, it's still work in progress and on a separate branch. Sources are available here: https://github.com/andysan/rfchameleon-fw/tree/wip-mcuboot

Happy to drop the bootloader PID until I have finished testing it if that makes any difference.

2024-02-02 17:41 UTC, tannewt commented
No problem.

2024-02-02 17:41 UTC, tannewt approved these changes

2024-02-02 17:42 UTC, merged