0060 JS-Simsport
pidcodes/pidcodes.github.com pull request #933
Opened 2024-03-03 08:29 UTC by Jordessey

Hi There.

I am an enthusiast maker that is looking to create low cost hardware to allow people to build their dream sim racing/farming/flight rig without spending thousands of dollars.

2024-03-25 21:17 UTC, tannewt requested changes
hardware is easyeda json under MIT. Software is CPP arduino under MIT. One edit to get the CI test happy.

2024-03-25 21:17 UTC, tannewt commented on 1209/0060/index.md
> +owner: JS SimSport
```suggestion
owner: JS-SimSport

```

2024-03-26 00:10 UTC, Jordessey reviewed
Fixing Owner/Title

2024-03-26 00:10 UTC, Jordessey reviewed
Foxing Owner

2024-05-21 16:56 UTC, tannewt approved these changes

2024-05-21 16:56 UTC, merged