Request PID 2350 for CircuitArt RP2350 zero
pidcodes/pidcodes.github.com pull request #973
Opened 2024-09-12 04:37 UTC by CircuitART

CircuitArt RP2350 zero is an open-source dev board, based on the RP2350 Microcontroller 

PCB Data(Altium): https://github.com/CircuitART/RP2350zero/tree/main/HRW

2024-09-12 22:05 UTC, tannewt requested changes
What software will it run and where is its source?

2024-09-13 03:53 UTC, CircuitART commented
> What software will it run and where is its source?

CircuitPython 
source: https://github.com/CircuitART/circuitpython/tree/main/ports/raspberrypi/boards/circuitart_zero_2350W

2024-09-13 17:07 UTC, tannewt commented
Please include that in the repo's README too. This PR isn't a good long term place for it.

2024-09-13 17:16 UTC, CircuitART commented
Done, and a PR will be opened in adafruit circuitpython repo the current link will also be updated to adafruit repo once this pid pr is approved

2024-09-16 21:06 UTC, tannewt approved these changes
Thank you!

2024-09-16 21:06 UTC, merged