Suggest adding a short description
pidcodes/pidcodes.github.com pull request #974
Opened 2024-09-12 22:08 UTC by tannewt

2024-09-12 22:08 UTC, tannewt commented
@jeffpeng3

2024-10-11 13:23 UTC, henrikbrixandersen approved these changes

2024-10-11 13:31 UTC, dhalbert requested changes

2024-10-11 13:31 UTC, dhalbert commented on howto.md
> +Under the second triple-dashed line, you should write a short description of your project including what hardware and software is uses.
```suggestion
Under the second triple-dashed line, you should write a short description of your project including what hardware and software it uses.
```

2024-10-21 19:57 UTC, merged