add PID for ECCN M0
pidcodes/pidcodes.github.com pull request #988
Opened 2024-10-16 19:03 UTC by bradanlane

The Bradán Lane STUDIO has created a small PCB using the SAMD21G18 with 4MB of extra flash memory (intended for application data or for CircuitPython code and libraries). It also contains touch pads, a buzzer, and LEDs.

The design is suitable for created a macropad or a small game.

This pull request is to provide a PID for the ECCN M0 for both C/C++ programming and CircuitPython.

2024-10-21 20:17 UTC, tannewt requested changes
Please link to the software that this will run and use the PID. (For example, your branch of CircuitPython that adds support.)

Hardware files are Kicad and fine.

2024-10-21 20:17 UTC, tannewt commented on 1209/5687/index.md
> +The ECCN M0 is a small SAMD21G18 design with 4MB flash, touch pads, LEDs, and a buzzer. It supports both C/C++ and CircuitPython. An example use for teh the ECCN M0 would be a 3-button macropad.
```suggestion
The ECCN M0 is a small SAMD21G18 design with 4MB flash, touch pads, LEDs, and a buzzer. It supports both C/C++ and CircuitPython. An example use for the the ECCN M0 would be a 3-button macropad.
```

2024-11-08 00:29 UTC, bradanlane commented
The

How do I include a "source" url for the hardware design plus a "source" url for the CircuitPython firmware as there is only a single field?

The branch for CircuitPython is:

https://github.com/bradanlane/circuitpython/tree/bls_coin_m0

A PR merge is pending review.

2024-11-08 00:34 UTC, bradanlane commented
_sorry for the typos in the code change commit comment_

2024-11-08 18:38 UTC, bradanlane commented on 1209/5687/index.md
> +The ECCN M0 is a small SAMD21G18 design with 4MB flash, touch pads, LEDs, and a buzzer. It supports both C/C++ and CircuitPython. An example use for teh the ECCN M0 would be a 3-button macropad.
corrected typo

2024-11-25 23:32 UTC, merged