Request PID 7691, 7692, 7639 for SlimeNRF devices
pidcodes/pidcodes.github.com pull request #990
Opened 2024-10-17 19:45 UTC by sctanf

Add bootloader PID for previous SlimeNRF Receiver (7690) and PIDs for tracker device and tracker bootloader
Hardware designs at:
https://github.com/SlimeVR/SlimeNRF-PCB
https://oshwlab.com/sctanf/slimenrf3

2024-10-21 20:22 UTC, tannewt requested changes
Where is the source code for the bootloader?

2024-10-21 20:27 UTC, sctanf commented
We are using the Adafruit nRF52 Bootloader
https://github.com/SlimeVR/Adafruit_nRF52_Bootloader

2024-11-25 23:34 UTC, tannewt commented
Please set the `source:` for the bootloader pids to that. Thank!

2024-11-26 20:05 UTC, tannewt approved these changes
Thanks for the update!

2024-11-26 20:06 UTC, merged